baseurl = "https://businessanalyticsorganization.github.io"
title = "Business Analytics Organization"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
resourceDir = "../resources"
publishDir = "docs"


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 7 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "Black"
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5

  # And you can even create generic menu
  [[menu.main]]
    identifier = "About"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "Contact"
    name       = "Contact"
    url        = "/contact"

  [[menu.main]]
    identifier = "Events"
    name       = "Events"
    url        = "/events"

  [[menu.main]]
    identifier = "Leadership"
    name       = "Leadership"
    url        = "/board"

  [[menu.main]]
    identifier = "Membership"
    name       = "Membership"
    url        = "/membership"

  [[menu.main]]
    identifier = "Newsletter"
    name       = "Newsletter"
    url        = "/newsletter"










